Puhk/Models/OsakonnaPuhkusedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Puhk.Models
{
    public class OsakonnaPuhkusedViewModel
    {
        public string Nimetus { get; set; }
        public List<Puhkus> Puhkused { get; set; }
    }
}

Puhk/Models/Puhkus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace Puhk.Models
{
    public class Puhkus
    {
        
        public int Id { get; set; }

        [Required(ErrorMessage = "Kohustuslik väli")]
        public Tüüp PuhkuseTüüp { get; set; }

        [Required(ErrorMessage = "Kohustuslik väli")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Puhkuse algus")]
        public DateTime AlgusKP { get; set; }
        
        [Required(ErrorMessage = "Kohustuslik väli")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Puhkuse lõpp")]
        public DateTime LõppKP { get; set; }

        [Required(ErrorMessage = "Kohustuslik väli")]
        public int TöötajaId { get; set; }

        public virtual Töötaja Töötaja { get; set; }

        public string Staatus { get; set; }

        public enum Tüüp { Tavapuhkus, Lapsehoolduspuhkus, Õppepuhkus }
        

    }
}

Puhk/Controllers/PuhkusController.cs
using Puhk.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Collections.Generic;
using System;

namespace Puhk.Controllers
{
    public class PuhkusController : Controller
    {
        private PuhkContext db = new PuhkContext();

        // GET: Puhkus
        //public ActionResult Index()
        //{
        //    //var puhkused = db.Puhkused.Include(p => p.Töötaja);
        //    //return View(puhkused.ToList());
            
        //}

        // GET: Puhkus/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Puhkus puhkus = db.Puhkused.Find(id);
                if (puhkus == null)
                {
                    return HttpNotFound();
                }
                return View(puhkus);
            }
            return RedirectToAction("Index", "Home");


            
        }
        
        // GET: Puhkus/Create
        public ActionResult Create(int? id)
        {
            //ViewBag.TöötajaId = new SelectList(db.Töötajad, "Id", "Nimi");
            //if (id == null)
            //{
            //    // siis mitte ei anna viga vaid paned siia asemele sisseloginud isiku ID

            //    //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Töötaja t = db.Töötajad.Find(id.Value);
            //if (t == null)
            //{
            //    return HttpNotFound();
            //}
            ////kas see id on selle töötaja id ja kui ei ole, kas töötaja on
            //// sama osakonna juhataja - siis select listis SELLE osakonna töötajad
            //// HR
            //// juku - nendel kahel select listis kõik töötajad
            //return View();

            if (Request.IsAuthenticated)
            {
                ViewBag.TöötajaId = new SelectList(db.Töötajad, "Id", "Nimi", id);
                ViewBag.KasutajaVoli = true;                                                                   // false ja ture on valesti... vist
                return View();
            }
            return RedirectToAction("Index", "Home");
            
        }

        // POST: Puhkus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PuhkuseTüüp,AlgusKP,LõppKP,TöötajaId,Staatus")] Puhkus puhkus)
        {

            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    if (Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Töötaja)
                    {
                        Töötaja t = Töötaja.SisseloginudTöötaja;
                        if (t != null)
                        {
                            puhkus.TöötajaId = t.Id;
                            db.Puhkused.Add(puhkus);
                            db.SaveChanges();
                        }
                        return RedirectToAction("MinuPuhkus");
                    }
                    else
                    {
                        db.Puhkused.Add(puhkus);
                        db.SaveChanges();
                        return RedirectToAction("Koik");
                    }

                }

                ViewBag.TöötajaId = new SelectList(db.Töötajad, "Id", "Nimi", puhkus.TöötajaId);
                return View(puhkus);
            }
            return RedirectToAction("Index", "Home");
          
        }

        // GET: Puhkus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Puhkus puhkus = db.Puhkused.Find(id);
                if (puhkus == null)
                {
                    return HttpNotFound();
                }
                ViewBag.TöötajaId = new SelectList(db.Töötajad, "Id", "Nimi", puhkus.TöötajaId);
                return View(puhkus);
            }
            return RedirectToAction("Index", "Home");

           
        }

        // POST: Puhkus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PuhkuseTüüp,AlgusKP,LõppKP,TöötajaId,Staatus")] Puhkus puhkus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(puhkus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TöötajaId = new SelectList(db.Töötajad, "Id", "Nimi", puhkus.TöötajaId);
            return View(puhkus);
        }

        public ActionResult ArvutaPuhkusepäevadKokku()  //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        {
            var töötaja = Töötaja.SisseloginudTöötaja;
            var käesolevAasta = DateTime.Now.Year;
            var puhkused = db.Puhkused.Where(p => p.TöötajaId == töötaja.Id).ToList();
            double kõikPuhkusePäevadKokku = 0;
            foreach ( var puhkus in puhkused)
            {
                if(puhkus.AlgusKP.Year == käesolevAasta)
                {
                    var ühePuhkusePäevadKokku = (puhkus.LõppKP - puhkus.AlgusKP).TotalDays;
                    kõikPuhkusePäevadKokku += ühePuhkusePäevadKokku;
                }
            }
            return View(kõikPuhkusePäevadKokku);
        }

        public ActionResult KinnitaPuhkus(int id)
        {
                Puhkus puhkus = db.Puhkused.Find(id);
                if (puhkus != null)
                {
                    puhkus.Staatus = "Kinnitatud";
                    db.SaveChanges();
                }
                if (Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Osakonnajuht)
                {
                    return RedirectToAction("OsakonnaPuhkused");
                }
                else
                {
                    return RedirectToAction("Koik");
                }
        }
        public ActionResult TühistaPuhkus(int id)
        {
            Puhkus puhkus = db.Puhkused.Find(id);
            if (puhkus != null)
            {
                puhkus.Staatus = "Tühistatud";
                db.SaveChanges();
            }
            if (Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Osakonnajuht)
            {
                return RedirectToAction("OsakonnaPuhkused");
            }
            else
            {
                return RedirectToAction("Koik");
            }
        }

        public ActionResult MinuPuhkus()
        {
            if (Request.IsAuthenticated)
            {
                var töötaja = Töötaja.SisseloginudTöötaja;
                var puhkused = db.Puhkused.Where(x => x.TöötajaId == töötaja.Id).ToList();
                return View(puhkused);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult OsakonnaPuhkused(string search, string option)
        {
            Töötaja t = Töötaja.SisseloginudTöötaja;
            var osakond = t.OsakondId;
            var puhkused = db.Puhkused.Where(p => p.Töötaja.OsakondId == osakond).ToList();
            var model = new OsakonnaPuhkusedViewModel
            {
                //Nimetus = osakond.Nimetus,
                Puhkused = puhkused
            };

            if (option == "Nimi")                                                                               // see jupp teeb töötajate otsingut
            {

                model.Puhkused = t.Osakond.Töötajad.Where(x => x.Nimi.ToLower().StartsWith(search.ToLower()) || search == null).SelectMany(x => x.Puhkused).ToList();
            }
            else if (option == "Isikukood")
            {
                model.Puhkused = t.Osakond.Töötajad.Where(x => x.Isikukood.StartsWith(search) || search == null).SelectMany(x => x.Puhkused).ToList();
            }
            
            return View(model);
        }

        public ActionResult Koik(string option, string search)
        {
            var osakondadePuhkused = new List<OsakonnaPuhkusedViewModel>();
            var osakonnad = db.Osakonnad.Include(o => o.Töötajad).ToList();
            foreach (var osakond in osakonnad)
            {
                var osakonnaNimi = osakond.Nimetus;
                var puhkused = osakond.Töötajad.SelectMany(t => t.Puhkused);
                var osakonnaPuhkused = new OsakonnaPuhkusedViewModel
                {
                    Nimetus = osakonnaNimi,
                    Puhkused = puhkused.ToList()
                };
                osakondadePuhkused.Add(osakonnaPuhkused);
            }
            return View(osakondadePuhkused);
        }

        public ActionResult Index(int? id)
        {
            Töötaja töötaja = Töötaja.ByKontakt(User.Identity.Name);
            ViewBag.Töötaja = töötaja;
            ViewBag.Osakonnad = db.Osakonnad.ToList();
            if (id.HasValue && id.Value == 0)
            {
                var puhkused = db.Puhkused.Where(x => x.TöötajaId == töötaja.Id).ToList();
                return View("Index", puhkused);
            }
            if (töötaja.TöötajaRoll == Töötaja.Roll.Firmajuht || töötaja.TöötajaRoll == Töötaja.Roll.Personalijuht)
            {
                if (id != null)
                {

Puhk/Views/Puhkus/Create.cshtml
@model Puhk.Models.Puhkus
@using Puhk.Models
@{
    ViewBag.Title = "Lisa puhkus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    if (Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Töötaja)
    {
        <h3>Lisa oma puhkuse soov</h3>
    }
    else
    {
        <h3>Lisa puhkus</h3>
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PuhkuseTüüp, "Puhkuse tüüp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EnumDropDownListFor(model => model.PuhkuseTüüp, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PuhkuseTüüp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlgusKP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlgusKP, new { htmlAttributes = new { @class = "form-control algusKP"}})
                @Html.ValidationMessageFor(model => model.AlgusKP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LõppKP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LõppKP, new { htmlAttributes = new { @class = "form-control lõppKP" } })
                @Html.ValidationMessageFor(model => model.LõppKP, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Töötaja.SisseloginudTöötaja.TöötajaRoll != Töötaja.Roll.Töötaja)
        {
            if (Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Personalijuht && Töötaja.SisseloginudTöötaja.TöötajaRoll == Töötaja.Roll.Firmajuht)
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.TöötajaId, "Töötaja", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TöötajaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TöötajaId, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.TöötajaId, "Töötaja", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TöötajaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TöötajaId, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
        }

        <div class="form-group">
            <label class="control-label col-md-2">Valitud päevade arv</label>
            <div class="col-md-10">
                <span id="päevadeArv"></span>
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lisa" class="btn btn-warning btn-sm" />
        </div>
    </div>
    <br />
    <br />

    @*<th>
            <a href='@Url.Action("Create", "Töötaja")' class="btn btn-warning btn-sm">Lisa uus töötaja</a>
        </th>*@

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {

            function arvutaPuhkusePäevadeArv() {
                var algusKP = moment($(".algusKP").val(), "YYYY-MM-DD");
                var lõppKP = moment($(".lõppKP").val(), "YYYY-MM-DD");
                var päevadeArv = 0;
                if (algusKP.isValid() && lõppKP.isValid()) {
                    var päevadeArv = lõppKP.diff(algusKP, "days");
                    $("#päevadeArv").text(päevadeArv + " päeva");
                }
                if (!algusKP.isValid() || !lõppKP.isValid()) {
                    $("#päevadeArv").text("")
                }
                if (päevadeArv <= 0) {
                    $("#päevadeArv").text("")
                }
            }

            $(".algusKP").on("change", function () {
                arvutaPuhkusePäevadeArv();
            });

            $(".lõppKP").on("change", function () {
                arvutaPuhkusePäevadeArv();
            });
        })
    </script>

}

@*// dokumendi lisamise jaoks!!*@

@*<h2>Basic File Upload</h2>
    @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <label for="file">Upload Image:</label>
        <input type="file" name="file" id="file" /><br><br>
        <input type="submit" value="Upload Image" />
        <br><br>
        @ViewBag.Message
    }*@

Puhk/Views/Puhkus/Delete.cshtml
@model Puhk.Models.Puhkus

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Puhkus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Töötaja.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Töötaja.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuhkuseTüüp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuhkuseTüüp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlgusKP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlgusKP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LõppKP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LõppKP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @Html.ActionLink("Tagasi", "/Koik")
        </div>
    }
</div>

Puhk/Views/Puhkus/Details.cshtml
@model Puhk.Models.Puhkus

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Puhkus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Töötaja.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Töötaja.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuhkuseTüüp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuhkuseTüüp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlgusKP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlgusKP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LõppKP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LõppKP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Puhk/Views/Puhkus/Edit.cshtml
@model Puhk.Models.Puhkus

@{
    ViewBag.Title = "Muuda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Muuda</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Puhkus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.PuhkuseTüüp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PuhkuseTüüp, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PuhkuseTüüp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlgusKP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlgusKP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlgusKP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LõppKP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LõppKP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LõppKP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TöötajaId, "TöötajaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TöötajaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TöötajaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Puhk/Views/Puhkus/Index.cshtml
@model IEnumerable<Puhk.Models.Puhkus>
    @using Puhk.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Minu puhkused</h3>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Töötaja.Nimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PuhkuseTüüp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlgusKP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LõppKP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Staatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Töötaja.Nimi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PuhkuseTüüp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlgusKP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LõppKP)
            </td>
            <td>
                @if (item.Staatus != null)
                {
                    @Html.DisplayFor(m => item.Staatus)
                }
                else
                {
                    @:Kinnitamata
                }
            </td>
        </tr>
     }
</table>

Puhk/Views/Puhkus/MinuPuhkus.cshtml
@model IEnumerable<Puhk.Models.Puhkus>
@using Puhk.Models

@{
    ViewBag.Title = "Minu puhkused";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Minu puhkused</h3>

<br />
<th>
    <a class="btn btn-warning btn-sm" href="Create" role="button">Lisa uus puhkus</a>
</th>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PuhkuseTüüp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlgusKP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LõppKP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Staatus)
        </th>
    </tr>

    @foreach (var puhkus in Töötaja.SisseloginudTöötaja.Puhkused)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => puhkus.PuhkuseTüüp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => puhkus.AlgusKP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => puhkus.LõppKP)
            </td>
            <td>
                @if (puhkus.Staatus != null)
                {
                    @Html.DisplayFor(m => puhkus.Staatus)
                }
                else
                {
                    @:Kinnitamata
                }
            </td>
        </tr>
    }
</table>

Puhk/Views/Puhkus/OsakonnaPuhkused.cshtml
@model Puhk.Models.OsakonnaPuhkusedViewModel
@using Puhk.Models

@{
    ViewBag.Title = "Osakonna puhkused";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("OsakonnaPuhkused", "Puhkus", FormMethod.Get))
{
    <hr/>
    <b> Otsingu valik: </b>
    @Html.RadioButton("option", "Nimi") <text>Nimi</text>
    if (Töötaja.SisseloginudTöötaja.TöötajaRoll != Töötaja.Roll.Töötaja && Töötaja.SisseloginudTöötaja.TöötajaRoll != Töötaja.Roll.Osakonnajuht)
    {
        @Html.RadioButton("option", "Isikukood") <text>Isikukood</text>
    }
    @Html.TextBox("search")
    <input type="submit"
           name="submit"
           value="Otsi"
           class="btn btn-warning btn-sm" />
}
    <hr/>


<h3>@Töötaja.SisseloginudTöötaja.Osakond.Nimetus</h3>

<br />

<table class="table">
    <tr>
        <th>Töötaja nimi</th>
        <th>Puhkuse tüüp</th>
        <th>Puhkuse alguskuupäev</th>
        <th>Puhkuse lõppkuupäev</th>
        <th>Staatus</th>
        <th></th>
    </tr>
    @foreach (var puhkus in Model.Puhkused)
    {
        <tr>
            <td>@Html.DisplayFor(m => puhkus.Töötaja.Nimi)</td>
            <td>@Html.DisplayFor(m => puhkus.PuhkuseTüüp)</td>
            <td>@Html.DisplayFor(m => puhkus.AlgusKP)</td>
            <td>@Html.DisplayFor(m => puhkus.LõppKP)</td>
            <td>

                @if (puhkus.Staatus != null)
                {
                    @Html.DisplayFor(m => puhkus.Staatus)
                }
                else
                {
                    @:Kinnitamata
                }
            </td>


            <td>
                @if (Töötaja.SisseloginudTöötaja.TöötajaRoll != Töötaja.Roll.Töötaja)
                {
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tegevused <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            @if (Töötaja.SisseloginudTöötaja.TöötajaRoll != Töötaja.Roll.Osakonnajuht)
                            {
                                <li>@Html.ActionLink("Muuda", "Edit", new { id = puhkus.Id })</li>
                                <li>@Html.ActionLink("Kustuta", "Delete", new { id = puhkus.Id })</li>

                            }

                            <li>@Html.ActionLink("Vaata", "Details", new { id = puhkus.Id })</li>

                            @if (Töötaja.SisseloginudTöötaja.Id != puhkus.Töötaja.Id)
                            {
                                <li>@Html.ActionLink("Kinnita", "KinnitaPuhkus", new { id = puhkus.Id })</li>
                                <li>@Html.ActionLink("Tühista", "TühistaPuhkus", new { id = puhkus.Id })</li>
                            }

                        </ul>
                    </div>
                }
            </td>
        </tr>
    }
</table>