Puhk/Models/Osakond.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace Puhk.Models
{
    public class Osakond
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Kohustuslik väli")]
        public string Nimetus { get; set; }

        public virtual ICollection<Töötaja> Töötajad { get; set; }


    }
}

Puhk/Controllers/OsakondController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Puhk.Models;
using Puhk;

namespace Puhk.Controllers
{
    public class OsakondController : Controller
    {
        private PuhkContext db = new PuhkContext();

        // GET: Osakond
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return View(db.Osakonnad.ToList());
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Osakond/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osakond osakond = db.Osakonnad.Find(id);
            if (osakond == null)
            {
                return HttpNotFound();
            }
            return View(osakond);
        }

        // GET: Osakond/Create
        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Osakond/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nimetus")] Osakond osakond)
        {
            if (ModelState.IsValid)
            {
                db.Osakonnad.Add(osakond);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(osakond);
        }

        // GET: Osakond/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Osakond osakond = db.Osakonnad.Find(id);
                if (osakond == null)
                {
                    return HttpNotFound();
                }
                return View(osakond);
            }
            return RedirectToAction("Index", "Home");
            
        }

        // POST: Osakond/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nimetus")] Osakond osakond)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osakond).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(osakond);
        }

        // GET: Osakond/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Osakond osakond = db.Osakonnad.Find(id);
                if (osakond == null)
                {
                    return HttpNotFound();
                }
                return View(osakond);
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Osakond/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Osakond osakond = db.Osakonnad.Find(id);
            db.Osakonnad.Remove(osakond);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Puhk/Views/Osakond/Create.cshtml
@model Puhk.Models.Osakond

@{
    ViewBag.Title = "Lisa osakond";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Lisa osakond</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lisa" class="btn btn-warning btn-sm" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Puhk/Views/Osakond/Delete.cshtml
@model Puhk.Models.Osakond

@{
    ViewBag.Title = "Kustuta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kustuta</h3>

<h4>Oled sa kindel, et soovid osakonda kustutada?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimetus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @Html.ActionLink("Tagasi", "Index")
        </div>
    }
</div>

Puhk/Views/Osakond/Details.cshtml
@model Puhk.Models.Osakond

@{
    ViewBag.Title = "Osakonna andmed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Osakonna andmed</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimetus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Muuda", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tagasi", "Index")
</p>

Puhk/Views/Osakond/Edit.cshtml
@model Puhk.Models.Osakond

@{
    ViewBag.Title = "Muuda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Muuda</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvesta" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Puhk/Views/Osakond/Index.cshtml
@model IEnumerable<Puhk.Models.Osakond>

@{
    ViewBag.Title = "Osakonnad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Osakonnad</h3>
<br />
<th>
    <a href='@Url.Action("Create", "Osakond")' class="btn btn-warning btn-sm">Lisa uus osakond</a>
</th>
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nimetus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nimetus)
            </td>
            <td>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Tegevused <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Muuda", "Edit", new { id = item.Id })</li>
                        <li>@Html.ActionLink("Vaata", "Details", new { id = item.Id })</li>
                        <li>@Html.ActionLink("Kustuta", "Delete", new { id = item.Id })</li>
                    </ul>
                </div>
            </td>
        </tr>
    }

</table>